// 翻譯與日文對照用物件
export const CATEGORY_TRANSLATION_MAP: Record<
  string,
  { zh: string; jp: string }
> = {
  // --- 麵類 ---
  ramen: { zh: "拉麵", jp: "ラーメン" },
  ramen_tokyo: { zh: "拉麵 (東京)", jp: "ラーメン TOKYO" },
  ramen_east: { zh: "拉麵 (東日本)", jp: "ラーメン EAST" },
  ramen_west: { zh: "拉麵 (西日本)", jp: "ラーメン WEST" },
  ramen_hokkaido: { zh: "拉麵 (北海道)", jp: "ラーメン 北海道" },
  ramen_kanagawa: { zh: "拉麵 (神奈川)", jp: "ラーメン 神奈川" },
  ramen_aichi: { zh: "拉麵 (愛知)", jp: "ラーメン 愛知" },
  ramen_osaka: { zh: "拉麵 (大阪)", jp: "ラーメン 大阪" },
  soba: { zh: "蕎麥麵", jp: "そば" },
  soba_east: { zh: "蕎麥麵 (東日本)", jp: "そば EAST" },
  soba_west: { zh: "蕎麥麵 (西日本)", jp: "そば WEST" },
  udon: { zh: "烏龍麵", jp: "うどん" },
  udon_kagawa: { zh: "烏龍麵 (香川)", jp: "うどん 香川" },
  udon_east: { zh: "烏龍麵 (東日本)", jp: "うどん EAST" },
  udon_west: { zh: "烏龍麵 (西日本)", jp: "うどん WEST" },
  yakisoba: { zh: "炒麵", jp: "焼きそば" },
  pasta: { zh: "義大利麵", jp: "パスタ" },

  // --- 日本料理 / 海鮮 / 鍋物 ---
  japanese: { zh: "日本料理", jp: "日本料理" },
  japanese_tokyo: { zh: "日本料理 (東京)", jp: "日本料理 TOKYO" },
  japanese_east: { zh: "日本料理 (東日本)", jp: "日本料理 EAST" },
  japanese_west: { zh: "日本料理 (西日本)", jp: "日本料理 WEST" },
  sushi: { zh: "壽司", jp: "寿司" },
  sushi_tokyo: { zh: "壽司 (東京)", jp: "寿司 TOKYO" },
  sushi_east: { zh: "壽司 (東日本)", jp: "寿司 EAST" },
  sushi_west: { zh: "壽司 (西日本)", jp: "寿司 WEST" },
  tempura: { zh: "天婦羅", jp: "天ぷら" },
  unagi: { zh: "鰻魚", jp: "うなぎ" },
  fugu: { zh: "河豚", jp: "ふぐ" },
  crab: { zh: "螃蟹", jp: "かに" },
  oden: { zh: "關東煮", jp: "おでん" },
  sukiyaki_shabushabu: { zh: "壽喜燒・涮涮鍋", jp: "すき焼き・しゃぶしゃぶ" },
  motsunabe: { zh: "牛雜鍋", jp: "もつ鍋" },

  // --- 肉類 ---
  yakiniku: { zh: "燒肉", jp: "焼肉" },
  yakiniku_tokyo: { zh: "燒肉 (東京)", jp: "焼肉 TOKYO" },
  yakiniku_east: { zh: "燒肉 (東日本)", jp: "焼肉 EAST" },
  yakiniku_west: { zh: "燒肉 (西日本)", jp: "焼肉 WEST" },
  steak: { zh: "牛排・鐵板燒", jp: "ステーキ・鉄板焼き" },
  steak_east: { zh: "牛排・鐵板燒 (東日本)", jp: "ステーキ・鉄板焼き EAST" },
  steak_west: { zh: "牛排・鐵板燒 (西日本)", jp: "ステーキ・鉄板焼き WEST" },
  tonkatsu: { zh: "炸豬排", jp: "とんかつ" },
  burger: { zh: "漢堡", jp: "ハンバーガー" },
  hamburger: { zh: "漢堡", jp: "ハンバーガー" },
  jingisukan: { zh: "成吉思汗烤肉", jp: "ジンギスカン" },

  // --- 雞肉 ---
  yakitori: { zh: "燒鳥 (串燒)", jp: "焼き鳥" },
  yakitori_east: { zh: "燒鳥 (東日本)", jp: "焼き鳥 EAST" },
  yakitori_west: { zh: "燒鳥 (西日本)", jp: "焼き鳥 WEST" },
  toriryori: { zh: "雞肉料理", jp: "鳥料理" },

  // --- 西式 / 各國料理 ---
  french: { zh: "法式料理", jp: "フレンチ" },
  french_tokyo: { zh: "法式料理 (東京)", jp: "フレンチ TOKYO" },
  french_east: { zh: "法式料理 (東日本)", jp: "フレンチ EAST" },
  french_west: { zh: "法式料理 (西日本)", jp: "フレンチ WEST" },
  italian: { zh: "義大利料理", jp: "イタリアン" },
  italian_tokyo: { zh: "義大利料理 (東京)", jp: "イタリアン TOKYO" },
  italian_east: { zh: "義大利料理 (東日本)", jp: "イタリアン EAST" },
  italian_west: { zh: "義大利料理 (西日本)", jp: "イタリアン WEST" },
  chinese: { zh: "中華料理", jp: "中国料理" },
  chinese_tokyo: { zh: "中華料理 (東京)", jp: "中国料理 TOKYO" },
  chinese_east: { zh: "中華料理 (東日本)", jp: "中国料理 EAST" },
  chinese_west: { zh: "中華料理 (西日本)", jp: "中国料理 WEST" },
  spanish: { zh: "西班牙料理", jp: "スペイン料理" },
  thai: { zh: "泰式料理", jp: "タイ料理" },
  indian: { zh: "印度料理", jp: "インド料理" },
  korean: { zh: "韓國料理", jp: "韓国料理" },
  asia_ethnic: { zh: "亞洲・異國料理", jp: "アジア・エスニック" },
  asia_ethnic_tokyo: { zh: "亞洲・異國料理 (東京)", jp: "アジア・エスニック TOKYO" },
  asia_ethnic_east: { zh: "亞洲・異國料理 (東日本)", jp: "アジア・エスニック EAST" },
  asia_ethnic_west: { zh: "亞洲・異國料理 (西日本)", jp: "アジア・エスニック WEST" },
  vietnam: { zh: "越南料理", jp: "ベトナム料理" },
  pizza: { zh: "披薩", jp: "ピザ" },
  bistro: { zh: "小酒館・洋食", jp: "ビストロ" },
  yoshoku: { zh: "日式洋食", jp: "洋食" },
  yoshoku_east: { zh: "日式洋食 (東日本)", jp: "洋食 EAST" },
  yoshoku_west: { zh: "日式洋食 (西日本)", jp: "洋食 WEST" },
  curry: { zh: "咖哩", jp: "カレー" },
  curry_tokyo: { zh: "咖哩 (東京)", jp: "カレー TOKYO" },
  curry_east: { zh: "咖哩 (東日本)", jp: "カレー EAST" },
  curry_west: { zh: "咖哩 (西日本)", jp: "カレー WEST" },
  gyoza: { zh: "餃子", jp: "餃子" },
  creative_innovative: { zh: "創新料理", jp: "創作料理・イノベーティブ" },

  // --- 居酒屋 / 酒 / 輕食 ---
  izakaya: { zh: "居酒屋", jp: "居酒屋" },
  izakaya_east: { zh: "居酒屋 (東日本)", jp: "居酒屋 EAST" },
  izakaya_west: { zh: "居酒屋 (西日本)", jp: "居酒屋 WEST" },
  bar: { zh: "酒吧", jp: "バー" },
  tachinomi: { zh: "立吞 (站著喝)", jp: "立ち飲み" },
  cafe: { zh: "咖啡廳", jp: "カフェ" },
  cafe_east: { zh: "咖啡廳 (東日本)", jp: "カフェ EAST" },
  cafe_west: { zh: "咖啡廳 (西日本)", jp: "カフェ WEST" },
  kissaten: { zh: "純喫茶 (老派咖啡店)", jp: "喫茶店" },
  tea: { zh: "紅茶・專門茶", jp: "紅茶" },
  bread: { zh: "麵包", jp: "パン" },
  bread_tokyo: { zh: "麵包 (東京)", jp: "パン TOKYO" },
  bread_east: { zh: "麵包 (東日本)", jp: "パン EAST" },
  bread_west: { zh: "麵包 (西日本)", jp: "パン WEST" },
  sweets: { zh: "甜點", jp: "スイーツ" },
  sweets_tokyo: { zh: "甜點 (東京)", jp: "スイーツ TOKYO" },
  sweets_east: { zh: "甜點 (東日本)", jp: "スイーツ EAST" },
  sweets_west: { zh: "甜點 (西日本)", jp: "スイーツ WEST" },
  wagashi: { zh: "和菓子 (日式甜點)", jp: "和菓子・甘味処" },
  wagashi_tokyo: { zh: "和菓子 (東京)", jp: "和菓子・甘味処 TOKYO" },
  wagashi_east: { zh: "和菓子 (東日本)", jp: "和菓子・甘味処 EAST" },
  wagashi_west: { zh: "和菓子 (西日本)", jp: "和菓子・甘味処 WEST" },
  shaved_ice: { zh: "刨冰", jp: "かき氷" },
  ice_gelato: { zh: "冰淇淋", jp: "アイス・ジェラート" },
  shochu: { zh: "燒酒", jp: "焼酎" },
  beer: { zh: "啤酒", jp: "ビアバー" },

  // --- 粉物 ---
  okonomiyaki: { zh: "大阪燒", jp: "お好み焼き" },
  shokudo: { zh: "定食・食堂", jp: "食堂" },
};